### ISSUE TITLE
Berilyum group_id yanlış verilmiş (api)

### ISSUE THREAD

**Issue by serhatyuna** [edisdev/periodic-table#2]
Berilyum'un group_id değeri 3 yerine 4 verilmiş.

![berilyum](https://user-images.githubusercontent.com/32708213/47312162-434c6380-d644-11e8-9089-bdcde4046194.png)

**Comment by edisdev** [comment]
Dikkatin için teşekkürler hemen düzeltiyorum 👍  :)

**Comment by edisdev** [comment]
Düzeltildi :)
