### ISSUE TITLE
el_order

### ISSUE THREAD

**Issue by gokaygurcan** [edisdev/periodic-table#4]
Merhaba,

https://periodic-table-10001.herokuapp.com/api/v1/elements 

```json
...
{
      "id": 8,
      "name_ing": "Oxygen",
      "name_tr": "Oksijen",
      "number": "8",
      "group_id": 1,
      "group_name": "Ametal",
      "name_small": "O",
      "row": 1,
      "column": 15,
      "molar": 15.9994,
      "el_order": 7,
      "created_at": "2018-10-15T20:06:30.055Z",
      "updated_at": "2018-10-15T20:06:30.055Z"
    },
    {
      "id": 7,
      "name_ing": "Nitrogen",
      "name_tr": "Azot",
      "number": "7",
      "group_id": 1,
      "group_name": "Ametal",
      "name_small": "N",
      "row": 1,
      "column": 14,
      "molar": 14.0067,
      "el_order": 7,
      "created_at": "2018-10-15T20:06:30.000Z",
      "updated_at": "2018-10-15T20:06:30.000Z"
    },
...
```

Şu iki element için `"el_order": 7,` değeri dönüyor. Tam olarak bununla mı alakalı incelemedim ama ekrana basarken O ve N yanlış sırayla basılıyor. 

<img width="306" alt="screen shot 2018-10-22 at 23 26 58" src="https://user-images.githubusercontent.com/1509413/47320580-1b63fc80-d652-11e8-92ec-2c9c59258b62.png">

Umarım sorunu anlayıp çözmeye yardımcı olur. 

Sevgiler,
G.

**Comment by edisdev** [comment]
Selamlar , evet sen söyleyince fark ettim dediğın gibi el_order ın aynı olmasıyla kaynaklı. En kısa sürede düzelticem. Issue ve yardmılar için teşekkürler :) 

Sevgi ve saygılar :)

**Comment by edisdev** [comment]
Hatta düzeltildi :)
