### ISSUE TITLE
Ametal nedir?

### ISSUE THREAD

**Issue by enderahmetyurt** [edisdev/periodic-table#5]
Merhaba Hatice,

Sağ taraftaki element tanımlarının üstüne gelince küçük bir pop-up ne olduğunu anlatsa belki benim gibi kimya cahilleri için daha iyi olabilir :)

**Comment by serhatyuna** [comment]
Benim aklıma da tıklandığında sadece seçilenlerin belirgin olması gelmişti.

**Comment by edisdev** [comment]
Çok güzel fikir bu tatil yapabilirim 👍  teşekkürler :)
